		<Page
			BackgroundColor='#333333'
			BackgroundOpacity='0.90'
			Location='804,400'
			MinimumSize='220,180'
			Name='AirspeederPanel'
			PackLocation='fff,nfn'
			PackSize='f,f'
			RStyleDefault='/Styles.New.tool.tool_tip.rs_default'
			ScrollExtent='240,180'
			Size='240,180'
			UserMovable='true'
			UserResizable='false'
			Visible='false'
		>
			<Data
				buttonBoost='buttonBoost'
				buttonSkyway='buttonSkyway'
				buttonTraffic='buttonTraffic'
				Name='CodeData'
			/>
			<Text
				Font='bold_12'
				LocalText='Skyway Controls'
				Location='8,6'
				Name='labelTitle'
				ScrollExtent='200,16'
				Size='200,16'
				TextColor='#FFFFFF'
			>Skyway Controls</Text>
			<Button
				LocalText='Enter Skyway'
				Location='10,30'
				Name='buttonSkyway'
				ScrollExtent='220,22'
				Size='220,22'
				Style='/Styles.New.buttons.hud.style'
			>Enter Skyway</Button>
			<Button
				LocalText='Boost Mode'
				Location='10,58'
				Name='buttonBoost'
				ScrollExtent='220,22'
				Size='220,22'
				Style='/Styles.New.buttons.hud.style'
			>Boost Mode</Button>
			<Button
				LocalText='Traffic Mode'
				Location='10,86'
				Name='buttonTraffic'
				ScrollExtent='220,22'
				Size='220,22'
				Style='/Styles.New.buttons.hud.style'
			>Traffic Mode</Button>
		</Page>
